// apps/cli/src/frameworks/react/strategy.ts
import { transform } from "@svgr/core";
import { eta } from "~/utils/eta";
import { enhancedConfirm } from "~/utils/prompts";
import {
  getA11yAttrs,
  SVG_OPENING_TAG_REGEX,
  SVG_TAG_REGEX,
  toReadableName,
} from "~/utils/svg";
import type {
  FrameworkStrategy,
  PromptContext,
  TemplateConfig,
  TransformSvgOptions,
} from "../types";
import { type ReactOptions, reactOptionsSchema } from "./schema";

const ICONS_TEMPLATE = `<% if (it.typescript) { -%>
export type IconProps = React.ComponentProps<"svg">;
<% if (it.forwardRef) { -%>
export type Icon = React.ForwardRefExoticComponent<IconProps & React.ComponentRef<"svg">>;
<% } else { -%>
export type Icon = (props: IconProps) => React.JSX.Element;
<% } -%>

export const Icons = {} as const satisfies Record<string, Icon>;

export type IconName = keyof typeof Icons;
<% } else { -%>
export const Icons = {};
<% } -%>
`;

const FOLDER_TEMPLATE = `import type { ComponentProps, JSX } from "react";

export type IconProps = ComponentProps<"svg">;

export function <%= it.componentName %>(props: IconProps): JSX.Element {
  return <%= it.svg %>;
}
`;

const FOLDER_FORWARDREF_TEMPLATE = `import { forwardRef, type ComponentProps, type ComponentRef } from "react";

export type IconProps = ComponentProps<"svg">;

export const <%= it.componentName %> = forwardRef<SVGSVGElement, IconProps>(
  function <%= it.componentName %>(props, ref) {
    return <%= it.svg %>;
  }
);

<%= it.componentName %>.displayName = "<%= it.componentName %>";
`;

eta.loadTemplate("@react/icons", ICONS_TEMPLATE);
eta.loadTemplate("@react/folder", FOLDER_TEMPLATE);
eta.loadTemplate("@react/folder-forwardref", FOLDER_FORWARDREF_TEMPLATE);

function getIconsTemplate(config: TemplateConfig): string {
  const opts = config.frameworkOptions as ReactOptions;
  const forwardRef = opts?.forwardRef ?? false;

  return eta.render("@react/icons", {
    typescript: config.typescript,
    forwardRef,
  });
}

/**
 * Transform SVG to React component using SVGR
 * Outputs camelCase attributes for JSX compatibility
 */
async function transformSvg(
  svg: string,
  options: TransformSvgOptions,
  frameworkOptions: ReactOptions
): Promise<string> {
  const { a11y, trackSource, iconName, componentName, outputMode } = options;
  const forwardRef = frameworkOptions?.forwardRef ?? false;
  const isFolderMode = outputMode === "folder";

  const svgProps: Record<string, string> = getA11yAttrs(a11y, componentName);

  if (trackSource && iconName) {
    svgProps["data-icon"] = iconName;
  }

  const jsCode = await transform(
    svg,
    {
      plugins: ["@svgr/plugin-svgo", "@svgr/plugin-jsx"],
      svgoConfig: {
        plugins: [
          "preset-default",
          "convertStyleToAttrs",
          "sortAttrs",
          "mergePaths",
        ],
      },
      jsxRuntime: "automatic",
      typescript: false,
      expandProps: "end",
      svgProps,
      titleProp: a11y === "title",
    },
    { componentName: "Icon" }
  );

  // Extract just the SVG JSX from the generated component
  const svgMatch = jsCode.match(SVG_TAG_REGEX);
  if (!svgMatch) {
    throw new Error("Failed to extract SVG from SVGR output");
  }

  let result = svgMatch[0];

  // For title mode, inject the title element with the readable name
  if (a11y === "title") {
    const readableName = toReadableName(componentName);
    result = result.replace(
      SVG_OPENING_TAG_REGEX,
      `<svg$1><title>${readableName}</title>`
    );
  }

  if (isFolderMode) {
    // Folder mode: generate standalone named export
    if (forwardRef) {
      result = result.replace(SVG_OPENING_TAG_REGEX, "<svg$1 ref={ref}>");
      return eta.render("@react/folder-forwardref", {
        componentName,
        svg: result,
      });
    }
    return eta.render("@react/folder", {
      componentName,
      svg: result,
    });
  }

  // File mode: generate object property
  if (forwardRef) {
    result = result.replace(SVG_OPENING_TAG_REGEX, "<svg$1 ref={ref}>");
    return `${componentName}: forwardRef<SVGSVGElement, IconProps>((props, ref) => (${result}))`;
  }

  return `${componentName}: (props) => (${result})`;
}

export const reactStrategy: FrameworkStrategy = {
  name: "react",

  fileExtensions: {
    typescript: ".tsx",
    javascript: ".jsx",
  },

  optionsSchema: reactOptionsSchema,

  supportsRef: true,

  preferredOutputType: "file",

  getIconsTemplate,

  getImports(options: ReactOptions) {
    if (options?.forwardRef) {
      return ['import { forwardRef } from "react";'];
    }
    return [];
  },

  getForwardRefImportSource() {
    return "react";
  },

  isForwardRefEnabled(options: ReactOptions) {
    return options?.forwardRef === true;
  },

  async promptOptions(context: PromptContext) {
    const forwardRef =
      context.forwardRef ??
      (await enhancedConfirm({
        message: "Use forwardRef for icon components?",
        initialValue: false,
      }));

    return { forwardRef };
  },

  getConfigKey() {
    return "react";
  },

  transformSvg,
};

// apps/cli/src/frameworks/solid/strategy.ts
import { eta } from "~/utils/eta";
import {
  getA11yAttrs,
  injectSvgTitle,
  optimizeSvg,
  SVG_OPENING_TAG_REGEX,
  toReadableName,
} from "~/utils/svg";
import type {
  FrameworkStrategy,
  TemplateConfig,
  TransformSvgOptions,
} from "../types";
import { type SolidOptions, solidOptionsSchema } from "./schema";

const ICONS_TEMPLATE = `<% if (it.typescript) { -%>
import type { ComponentProps, JSX } from "solid-js";

export type IconProps = ComponentProps<"svg">;
export type Icon = (props: IconProps) => JSX.Element;

export const Icons = {} as const satisfies Record<string, Icon>;

export type IconName = keyof typeof Icons;
<% } else { -%>
export const Icons = {};
<% } -%>
`;

const FOLDER_TEMPLATE = `import type { ComponentProps, JSX } from "solid-js";

export type IconProps = ComponentProps<"svg">;

export function <%= it.componentName %>(props: IconProps): JSX.Element {
  return <%= it.svg %>;
}
`;

eta.loadTemplate("@solid/icons", ICONS_TEMPLATE);
eta.loadTemplate("@solid/folder", FOLDER_TEMPLATE);

function getIconsTemplate(config: TemplateConfig): string {
  return eta.render("@solid/icons", {
    typescript: config.typescript,
  });
}

/**
 * Transform SVG to Solid component
 * Uses native HTML attributes (kebab-case) since Solid supports them
 */
function transformSvg(
  svg: string,
  options: TransformSvgOptions
): Promise<string> {
  const { a11y, trackSource, iconName, componentName, outputMode } = options;
  const isFolderMode = outputMode === "folder";

  // Optimize SVG with SVGO (keeps kebab-case attributes)
  let result = optimizeSvg(svg);

  // Build extra attributes
  const extraAttrs: Record<string, string> = getA11yAttrs(a11y, componentName);

  if (trackSource && iconName) {
    extraAttrs["data-icon"] = iconName;
  }

  // Inject extra attributes into SVG opening tag
  if (Object.keys(extraAttrs).length > 0) {
    const attrString = Object.entries(extraAttrs)
      .map(([k, v]) => `${k}="${v}"`)
      .join(" ");
    result = result.replace(SVG_OPENING_TAG_REGEX, `<svg$1 ${attrString}>`);
  }

  // For title mode, inject the title element
  if (a11y === "title") {
    const readableName = toReadableName(componentName);
    result = injectSvgTitle(result, readableName);
  }

  // Add props spreading - Solid uses native spread syntax
  result = result.replace(SVG_OPENING_TAG_REGEX, "<svg$1 {...props}>");

  if (isFolderMode) {
    // Folder mode: generate standalone named export
    return Promise.resolve(
      eta.render("@solid/folder", {
        componentName,
        svg: result,
      })
    );
  }

  // File mode: generate object property
  return Promise.resolve(`${componentName}: (props) => (${result})`);
}

export const solidStrategy: FrameworkStrategy = {
  name: "solid",

  fileExtensions: {
    typescript: ".tsx",
    javascript: ".jsx",
  },

  optionsSchema: solidOptionsSchema,

  supportsRef: true,

  preferredOutputType: "file",

  getIconsTemplate,

  getImports(_options: SolidOptions) {
    // Solid doesn't need forwardRef import - refs work as regular props
    return [];
  },

  getForwardRefImportSource() {
    return "solid-js";
  },

  isForwardRefEnabled(_options: SolidOptions) {
    // Solid doesn't use forwardRef pattern
    return false;
  },

  promptOptions() {
    // Solid has no framework-specific options to prompt for
    return Promise.resolve({});
  },

  getConfigKey() {
    return "solid";
  },

  transformSvg,
};
